# ==============================================================================
# Nessie DB Backup Credentials (SeaweedFS S3)
# ==============================================================================
# SOPS encrypted - edit with: sops cluster/infrastructure/services/nessie/backup-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: nessie-db-backup-creds
    namespace: nessie
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:dtGwnVo=,iv:FpV6elKKy0uG4utGwKMSsWs2jiYQfufGpKiTxw92LvA=,tag:ywKxSQFCPQFrtVRuNXUouA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:UKo9aC4=,iv:15iU2II/OsJxpHbQhaU79ft/ry8EVRQzbFFmzgmynCw=,tag:um8CkHpgpez/7aio53xyLA==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Ty82NHVGUWhFZG9NTjBp
            M2kzVHFrOWsxdENxbTVlRFNIOGJZL0R3OTBjClRHeko5eUpTQTdYY1A1VDlTMkVW
            UVdSR3NKKzNPN2lZc2pvRndYVDY3WDAKLS0tIGtTRDJNVzhqVEp4ZnBYSEtPamNT
            eDAwZ3d4MmEzajlOTlN1Y1hQMjQzd0EKiPRqqlWQj5YVnuG2MOImOCqXLpB6NE3x
            88hku7bkPEJcL3Uk6Xt/lxWKLp7Ygeo0LnxiGpRCE2Eg9OPhfes5Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T07:02:12Z"
    mac: ENC[AES256_GCM,data:a33NaxRt0gRLNC+d/GTHXjyUZDhZRlrcwkr1jX10bHXCWyHgTfKRUPT54ev+LTUvOdKOVDf1sZ1qrPPA1x5vuRvQ0x9LAayT5f/fLG7LqGgSR7FG5Q4cgYSqIYPdZccmCQzffkAaHnEtlcqpeUkEy4Ie4s7cift7DE85pViLEHY=,iv:A3lW9k1Nv8/xud/vu0Yoz4mux7zheUF6x09h8uEc7gw=,tag:BVGyEDEpOtP8RfkiAO3WIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
