# ==============================================================================
# Nessie Namespace
# ==============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: nessie
