# ==============================================================================
# SOPS Configuration
# ==============================================================================
# This file is auto-updated by Ansible during bootstrap
# The age key below will be replaced with your generated key
# ==============================================================================

creation_rules:
  - path_regex: clusters/.*secret.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: PLACEHOLDER_RUN_ANSIBLE_TO_GENERATE