apiVersion: v1
kind: Secret
metadata:
    name: ducklake-db-backup-creds
    namespace: lotus-lake
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:J3U37sTQg4Ygt1I=,iv:L4HH4WufsZcw+CCQ/iPQc+S6nscXC0MsjSHd4fbnNZc=,tag:7jZUa/RWmzgJfrOS6GrpNw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FoGAIn0ZqS704nedckw=,iv:YsQZ62xmysLHPtTy4wLiUfSar+Duhu4g08wE1gXNWEs=,tag:TaeELrZuzRCNuxfxOChUvA==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WWhPczNCdUY5dER6a2Qy
            d0xseHg5Y2xTQU16ZTU0cm9Vc3hhZkZBMkZzCmFzRWRNMjhIRWJFS0tYVUxqb016
            MjdhclYrNHM4UzFtWlRRZjg3RGJscjAKLS0tIDJBcU1QclRCUVE2NS8rc0VJeEU2
            NkJGUUl1bEFtS0pkK2J2cEh4ZVV4bWcK5id3617LuGU64nJcoPoWwNTUJkg9G/MZ
            EnV3wAM2g96S38tX9Aapc0bwN2CwoBbFIK/SDJQVaNrJKdcwk19YkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T06:17:54Z"
    mac: ENC[AES256_GCM,data:PRkFSkjk5c2CvP10791IGHn6wVdlxowWTrhI4fbBg+jk/MCugoTWF/+q3j6yTr+QArrQfb5fggPMeTNgF3NWIKlt33Pb4cVw1PQ8tXf6rtPQInRc7UepMRhRXAN6OiNSi5MYtIAf6L/neDw7yqaTXWNWsaWqOlpYR3d5GZAZxpU=,iv:uQ2wbllTr0PUDl9vxXEo+aXtzuFsFv218VBcD1bbHHg=,tag:kcH5KkkMbzvywiKrO1GOnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
