# ==============================================================================
# DuckLake DB Backup Credentials (SeaweedFS S3)
# ==============================================================================
# SOPS encrypted - edit with: sops cluster/namespaces/lotus-lake/ducklake-db-backup-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: ducklake-db-backup-creds
    namespace: lotus-lake
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:Py+GK7M=,iv:1FGZolnUTh8k6wdKefHHjVNA8AFzhMIiktca+Stt+Jk=,tag:cZIcP6ZaMT7AP9eVrMyT+Q==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:68naBxhSzdc=,iv:HacBySUZ/SPid7NB96+VX4Nbe/l+IkM7Dp6Q4bMtRNg=,tag:vOTj/V7rpb1IEuwTZRRrug==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MVJTeW1WUTJWUVUzLzFv
            TTBLT2h0Tkt1Z2JleGpaSFJOQVRNVFZxWmtFCm5vOVpYWXhtZjJuK1VzOHVmZ05Q
            RXdOckhQNmsvQVdOb2J3TEtFREIyaE0KLS0tIEVBeG12MzBPVmt0TFlVdEpENlhn
            L2RKanJ4MkdLZXdoV25aY1RiZXptbncKczMDRASIcXlncEmJRpUlYTDlwgc8CS5R
            Rb8rloggbPvYdP7j5rLz+th6OJZOf89N/53bPjloir+RyQMAq/pfIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T02:01:15Z"
    mac: ENC[AES256_GCM,data:WBq1+G+j9KvCxKY/7OnPfgieFFXcK6xTu79vbRhGeVLL32MvYQZA2YdSdqBnlHEfXuoidwFgGQXlSxCFI3gjoPKGYB3+tdSasD+Vn10C0tfwnUvo28fLmJJWs6JBF2evJqGH6dftIwA/Xy9oRkk8Urv6cpq5+acnmqUMEgkfmrw=,iv:ASA0r16CA0EZqwRrR3SDCMe3jz9uoSiHVWl4YVsuHgg=,tag:Va1PU1C+UVnrDjA4+3zvqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
