# ==============================================================================
# Lotus Lake Terraform Secrets
# ==============================================================================
# Secrets for Airbyte Terraform configuration
# ENCRYPT WITH: sops -e -i lotus-lake-secrets.yaml
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: lotus-lake-terraform-vars
    namespace: lotus-lake
type: Opaque
stringData:
    #ENC[AES256_GCM,data:8GvV68WavojjF60+Sq/KRJB+eDF480G9XO7qVPH8eegiRpscjP0Y/DauZUIFCH5OBhn5LcU=,iv:Eh9tAwUnP+t6bGkjcW1tJ2xlWxRWiL/dlCHCR2iCNdw=,tag:qwzxIZR8vla6AzevqvW0NA==,type:comment]
    workspace_id: ENC[AES256_GCM,data:W0DFrhjGNQwyiP5yR5WZQkq9Hafm2yoBHlY87QwBAiTOM/NQ,iv:AUa+GlhgZNTnwWqoUpLdURIRcKIasqnZTOFu0SMiFPU=,tag:3x6n5CYQzPksjoN4srOOfg==,type:str]
    airbyte_server_url: ENC[AES256_GCM,data:m64jfJQObkbL8vye23gYMOSrlA4Pix5XomvjETA4TV8b0MIYbmK+bmLkGJYclVsrgwCgWitBWTjAYSN2gMrLXWC5cqdI,iv:U0EWjv2jTrjQs68fz3v8was+MuHuVM9KRc7evqAakTs=,tag:GfYQnfJQKzEbbf+yYh2grA==,type:str]
    airbyte_username: ENC[AES256_GCM,data:G2H4UU4a6Q==,iv:IX9Gv8IbZCcYWZcMCmfNi+FFfU4oO542r+tzRp5bCM4=,tag:o1fohGttolZIngaXFKyIIg==,type:str]
    airbyte_password: ENC[AES256_GCM,data:5mPJPaazr+Y=,iv:Uzha9YPgsJJ4SD0KiETyGF+fPxviu5tDpAgjD8Amod8=,tag:CYsqlIWtRgPY1mww9DXb1A==,type:str]
    #ENC[AES256_GCM,data:yjTvUGl3Uwk=,iv:FFisuRPbDSi/sUKbAn5u5/ED7mLmRKf5Bvl2kq1ALjc=,tag:CA11YXjrxwBeVNk4D8UrBA==,type:comment]
    shopify_store: ENC[AES256_GCM,data:GQXY6Itn2daARXNcEtSo1IQwXvhbKl2f0e0=,iv:b2Xz22bBqcH/DGTu9CRlEjMnWvcC6lKfuRbeUVkqs/w=,tag:HqzIrFQPnGA05549xpWRAA==,type:str]
    shopify_api_password: ENC[AES256_GCM,data:447VlyaqTVKPPg5QHPlXWK+NmQtKix/2JPf67ioGB3/dZKCFkWI=,iv:joF9+NwBThVXk+b3ilrv0dpMiPgQDCkErRgxCPRB2pM=,tag:8dvSpkdnOvdsCCogoujwOQ==,type:str]
    #ENC[AES256_GCM,data:E/s7ZEaMu0o=,iv:jHK70MbZQfsiYo1774zl7iIuM/SfoYZPiTuP56HMIDw=,tag:pUm0akR2ycvADFYA1J/6FQ==,type:comment]
    klaviyo_api_key: ENC[AES256_GCM,data:qSygZetu7OjBKwFoZaBWURNDg4AbdhNIb7L57QVvStBsn/gr3A==,iv:KbMBMHtrz+20SMAjohJMqacaipOcPxNqUJqcHjJ6ahk=,tag:atHiUkpE5KxuG4UxJpkUqQ==,type:str]
    #ENC[AES256_GCM,data:IHo47qWFQVMRBq+pW27QfvjUl2ITtY6yk9y/6zU=,iv:UEMT29Pokg1t4/ZGtUFuEIzNIk6tYtSyM8oq6w4cQjk=,tag:MWNtmKigNM071/ORgA9+Vw==,type:comment]
    minio_user: ENC[AES256_GCM,data:AkR+We1Oc0uWcJFojA==,iv:JLp5smZ4SmuitxBibP6pb/2/lADCqzQvZxeLnh4UYMA=,tag:TvorGqgEo+Mgh5GvlPQVVg==,type:str]
    minio_password: ENC[AES256_GCM,data:Tyk9z3KhObgIzSU6NPs=,iv:zn1PZX9CIhl/8JudkCOxzZDzwOI980uaKUgmQcMKP8s=,tag:N3rsZ6oB+370ovfPQCoqyA==,type:str]
    minio_endpoint: ENC[AES256_GCM,data:TjMai9tRcfyshOXITJemQ6JCQ++cgJd9dO6dBqfFWI4ZLTzS0ZDF0kGbaP3zG/oMA13kSg==,iv:SqUVA7mgz4iMxlIAj8spL6YrxNquol6VOrFcl9e2ffQ=,tag:MpplFnDAXxNOYUg67IpnYw==,type:str]
    #ENC[AES256_GCM,data:UdB1tD4l1vtDZm3wIMDULBh+LY85rt/8AHsOQkW02Wj39ab8yHMB92wv,iv:3F5ExN8mohw2mr3aUTJ0YHcrimcS0FQX7tSRScwD09U=,tag:AcgT0TutQNnzJ4dUYWCmGQ==,type:comment]
    nessie_endpoint: ENC[AES256_GCM,data:C9RShwhoPrnIk0EidSQ918JjQoznrC950harjVsg0ulHKFv5Nz8sgBXA7DipS+lux3bS,iv:BsgilkMZdoN8XOc7vZAOWZ2oHMW5hsLgSCoqQIVJJGw=,tag:cow8UK9OFKxybvWB1O14tw==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0M0sxb1k0bHJmU2xvTENi
            ekVmRVdhMFc0aUVwY0tIZjRKWjl0K25MRmswCmQyMnNjY3AzMGs5ZmpUREZ2U01h
            TERRSG1lV3luVkFRV3BhR2tYTzErWlkKLS0tIE5UZlF6LzBtMTFERzVxMWJiditw
            cWtsMXB4blByVWdTYlM2QXhUSjFmS00K5y84ynaSmSUIrnHndgvyPUIM9BWk3Iqb
            0l4jlt6CRtHhrEFt8okl77AtwT8NAw5BIS9kSA79u4ae4pwvD2xKyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T06:17:46Z"
    mac: ENC[AES256_GCM,data:LV7MdHC+bD6e6Xn+oR9My93XmQj2H7zu9n+ytqtJbf3Nv7DIJn03HFdOUtcFcQ1Y+y8ayksFm6f7a0S66/7V/VLqXPZh7b9MFSfmQsFoM0Kpoa5FwMv8PuTfe3xZvGkxe/EfXGLdMwiFx4vyxItaUl3tBXGXKWuBKvpmJ+IEbbw=,iv:QI6QfX/ANkwBjpxijS7mypGX8dq23sk32J07/MUmB70=,tag:paS3GoXjnqy+Lb0qmf5izQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
