# ==============================================================================
# Lotus Lake Terraform Resource
# ==============================================================================
# Runs Terraform for Airbyte configuration via tofu-controller
# ==============================================================================

apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: lotus-lake-airbyte
  namespace: lotus-lake
spec:
  interval: 5m
  retryInterval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: true
  path: ./orchestration/airbyte/terraform
  sourceRef:
    kind: GitRepository
    name: lotus-lake
    namespace: lotus-lake
  varsFrom:
    - kind: Secret
      name: lotus-lake-terraform-vars
  runnerPodTemplate:
    spec:
      nodeSelector:
        node.h-kube.io/location: home
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - monkeybusiness
