# ==============================================================================
# Lotus Lake GitRepository
# ==============================================================================
# Source for lotus-lake data platform - Flux watches this repo for changes
# ==============================================================================

apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: lotus-lake
  namespace: lotus-lake
spec:
  interval: 5m
  url: ssh://git@forgejo.datamountainsolutions.com:2222/mkultra/lotus-lake
  ref:
    branch: main
  secretRef:
    name: flux-system
