# ==============================================================================
# Lotus Lake Terraform Secrets
# ==============================================================================
# Secrets for Airbyte Terraform configuration
# ENCRYPT WITH: sops -e -i lotus-lake-secrets.yaml
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: lotus-lake-terraform-vars
    namespace: lotus-lake
type: Opaque
stringData:
    #ENC[AES256_GCM,data:+U1kJBIVUaNOUO4Y3xLvEyujLf32l11kTwdQ59XFQQM6cq1y5vdBPhBFZcN86apQKXtweJU=,iv:l19zvUuQwTenPZ01mz+78T79I+b2SsoAl3A3HzNCcN4=,tag:nbW0yi8hHcsIgpfSqTvOuw==,type:comment]
    workspace_id: ENC[AES256_GCM,data:jWtRLcCqbndWnjtEX5GnJRs9RYvqAybRWAXZWBZS5IiotQPJ,iv:ovJ+8E04rRNzumIC/cwKK0MTbEXBUWutazYzpTBoRuw=,tag:Da21zSHcG98C6PgZtyPaTw==,type:str]
    airbyte_server_url: ENC[AES256_GCM,data:h1kZrxZU4JTxiyn3/YauvN0xbGhHR/C66Hq+h0/R6Hr4MWXdWp8/RsXnUBukd+c08eXOrgP500qC+uokjzphnhFlOxUp,iv:GTx6EyD1prhw5YXwkUMKsy2RFXhmGkLIiJIxkXFva90=,tag:9kmtTBdRcKArzdNLSZ3v4A==,type:str]
    airbyte_username: ENC[AES256_GCM,data:sqO+tYcv,iv:dtFgX7XJmvFdn0yr/1S9seJ4JGgc8SgBmRAb/AO8Oi0=,tag:S5nMqd6kxQwr6+AQP9CBAA==,type:str]
    airbyte_password: ENC[AES256_GCM,data:QUhSHWlQzzQ9gzd9kF4=,iv:9rK6h816PTunAojbbzrEWVykTGfXA3HoyNGjTNqF8AU=,tag:R9Zp+EcraHv2CEAt8Kqxxw==,type:str]
    #ENC[AES256_GCM,data:OnFe2/Zw6Ok=,iv:Tn7qOT1hq2ziICejV0SBcMT2dS1AOS/uH/UJNCycM/8=,tag:KDYGS9cUCRXG6qHa8k8LAg==,type:comment]
    shopify_store: ENC[AES256_GCM,data:alEUsunwx0Hj2WgEVvVrmD1yTI+LsZE/Sa8=,iv:9Urulth84mErBQuPDQKw5dJwvUJEmyDqOGoeZrhbXAM=,tag:2gGOQFX+cVcsOcBKlT2DNg==,type:str]
    shopify_api_password: ENC[AES256_GCM,data:uQBhulRukNEAj/RAtfPyGu+9eaGw9qt4+yAVAGr1XoWh9Fqj+3Y=,iv:ITQwLoNoJ34yL+3v71A5d8iobx1vbF74EHuPrl1QvbQ=,tag:WaQh3l/7W/L6zFuQy0vSUQ==,type:str]
    #ENC[AES256_GCM,data:8ALHonmVt7Y=,iv:gI9cDVNBmmpM0coXPKxupL7kmIyoJX2EdIDBSHkP2Ug=,tag:6TQR+sxaqmcAb+R5o2GU8A==,type:comment]
    klaviyo_api_key: ENC[AES256_GCM,data:k2ZBGl3NCUUdKFbM9yzPWymSX3CQ1DWoier6z3jt0R0b2MnCPg==,iv:g7rrKrTZGZOzcY2na31Hh2xdWFqR6dy7zrX3hSbNJi8=,tag:AWja9kHUnRwuIivLAsAH3g==,type:str]
    #ENC[AES256_GCM,data:sD7oMf+2rF6aOLXdxMwYsKGz6NoqX3PmgI0ZlTY=,iv:TQ/0NGEHEUbsJOFZ6Mmxg3pxEz73qsFh7Ov8I9Psn3c=,tag:7tjm11pDdFYn/wU/bhP8bg==,type:comment]
    s3_access_key_id: ENC[AES256_GCM,data:q09Ie3A/a5l/Gj/eJQ==,iv:LBsXvxCuX0JqOt0DqNRruSl7RnE20NBYHbh1v3JxVfg=,tag:QMAYlPUBVd7yR4/VjqfpVw==,type:str]
    s3_secret_access_key: ENC[AES256_GCM,data:gzAuAYTB0G6Pma7rQFI=,iv:XFI29JxZAiOKS+RrTFdlvpLEplZV2RRsTpCtkq9wN4M=,tag:rkOLslt3JPvU2buzWG6TlQ==,type:str]
    s3_endpoint: ENC[AES256_GCM,data:bVhkLWtjdx7exrhzFINfR60vqJ6tqXJ17BuRHasb7pLL6/Npmqp3U7+kmFQ13SBiInC5kg==,iv:ad0ED+9pKXCOzq6sCA816DKY+nqxYrTgW0fL9ZjdgLc=,tag:bGzXTG5t9Qf9D04IDWPjnA==,type:str]
    #ENC[AES256_GCM,data:ESieV8uu5yJDRFRXDXACfUkuRqZ4TNNxaoHVrbCHHxmJwoCniKBsGqI6,iv:jBT8t0qaoyNr3dP99+DbLqQWiSK8gMDdjZuAKZA3Xpk=,tag:5upwofHF9sAeaL9JMKHAWA==,type:comment]
    nessie_endpoint: ENC[AES256_GCM,data:rv3ISGo3mjt59eSyqo8SzN4y9sGAQ5QmNNUm/10Ue+a8/69Sa3VSvXK5luwVl/x7+TnA,iv:E7D6Dg9lWiL85Xl7jvLlonMJg6fs3Gw4TcVKff5aSkI=,tag:yKodnGPFFnM6STZyuINvPw==,type:str]
    #ENC[AES256_GCM,data:lBs86pU0MQ==,iv:0dKasg1KuMdNdkYDc669Q+xOPHFUEzI2vxP3l4OteY4=,tag:RW6zdx0Sq0olGdXU2ppaHA==,type:comment]
    cubejs_api_secret: ENC[AES256_GCM,data:68MhBQCrXZjEzO81MWHLikOJZ+ghYTUs3b1t/ztIy4E=,iv:dwN+qpu5oquH6/cOOo/Dv0LRmLBrf+pZ3AXkrybVPmU=,tag:Q5Na1iVaMQ6ojIn9IWc9rA==,type:str]
    #ENC[AES256_GCM,data:O4UuPvQ=,iv:5Cq9AT73vxLm2ehwvcZmMnCwW0efNuZbfoMSoPGykjc=,tag:RdIlQ72cT9Ts9JWNp7k29A==,type:comment]
    ODOO_URL: ENC[AES256_GCM,data:tpyJYrfEkZxO39NpK4GCcVvQGmIn5Q==,iv:GyH8ILnZrd+kQYKB2lXS8zZhrcQSWpyhsUxU/83wGjs=,tag:aD1Q/gQbE+49scPyrhsAWg==,type:str]
    ODOO_DB: ENC[AES256_GCM,data:N0VUEzY2NcKIo/W6gqJQNpAAgM1WjC9tcT4cF+gYmn9rPTZTn/w=,iv:q+Tyb9DtJIjYRDR/FZ2rKE5cj53fRUR1mbE2oQoUl88=,tag:w57/sfvvbIc67oHWL7pNGA==,type:str]
    ODOO_USER: ENC[AES256_GCM,data:aiEujqDFDlj9Y1bV5oMrWj8/zbIOT1AFSwtnzIYi,iv:y1v5A1wrzQs/EpP5OkCRSi5qB5La5snsgpvEWbZPnqM=,tag:IbD+U+/Tispw89ZhuFJrrA==,type:str]
    ODOO_PASSWORD: ENC[AES256_GCM,data:hwIpQD1d0FQ=,iv:mppnq98w+Uj276TEM6iVkhiOS9aO4Mfxbop1hLP0o+M=,tag:pgpYgtnN6dnuS7uBHx/LMA==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK2xOczZVbHVScW9LZUh4
            bm03czhHL3hYNlhiWHQ5UVhVRjIwSytmTEFrCmx2STBreUorR1FBZTlCTk15a2dh
            b0RVN1NUMDhLV2tPaGVjUWNjdEFrbjAKLS0tIDhwV1JwamM5YUQwSkhhN2pTTzBp
            SEhwVDB4YVYvbFVvY1IrRm45aUFwQVUK7nePuEOiQkZMDRZnvjIDOvUSgsEGmVF6
            kRJUItHe/t6XFuA9Mib7CyEhqmgbUTXYq+SmGNxa6W/2Xb/nSyjSaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T17:04:00Z"
    mac: ENC[AES256_GCM,data:ZrjUgHvPgYcGKGf/Gpxc8ir9hUqz+GtKOna+cfvlLA2Qv/AkWna69sMKGqavcQ4eCO5KQRD+vU5NVWnig4hAVEhlhhkHWwXoHzScvrKfPnv6sRjGhXbhVgDjIUW29Qmw9aw7ZwRmViB6+tkKSe6SMLGStnYumuRJBbRSHz4bgvI=,iv:sYXSYHLeV1/EM6F0Aay79wtPSVe6yZzuNRm8RAhKrIw=,tag:TXMvJfK6jIE/Z5Ds1IZJQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
