# ==============================================================================
# Homenetes GitRepository
# ==============================================================================
# Source for homelab applications - Flux watches this repo for changes
# ==============================================================================

apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homenetes
  namespace: flux-system
spec:
  interval: 5m
  url: ssh://git@forgejo.datamountainsolutions.com:2222/mkultra/homenetes
  ref:
    branch: main
  secretRef:
    name: flux-system
