# ==============================================================================
# Landl Plane Secrets
# ==============================================================================
# Entity-specific secrets for Plane deployment
# ENCRYPT WITH: sops -e -i plane-secrets.yaml
# ==============================================================================
# Database password for CNPG
apiVersion: v1
kind: Secret
metadata:
    name: landl-plane-db-password
    namespace: landl
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:O4SLE5U=,iv:9AAbWxkyHBu42OWzT+7wrNLhkzJtezJyFKiEtz0kdPQ=,tag:Uam21vOURVgOgT289cxd9g==,type:str]
    password: ENC[AES256_GCM,data:KtPIrm4I0aqQXAA2bhyFvsRYyE3jD5aXCwbG8UYdTK4=,iv:74OzWWIIzlUBb52hW1a4DEk7RrMCCnBl0Vr6DTdCjVM=,tag:V4wWOKf75OVYiTlU1ucfDg==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUjNHMDNGTk5kRlVHM0ZT
            SWlEdVpmTFJRM00wT1FFZHBtcHU0NVVNTW44CnBqWGtpUDZxMUhzQU1aSmRldUIy
            ck9WOHdUS2NLN3JDTnB5dGsyeE01ZmMKLS0tIDhoanpnbjF2VUdDMTA3QXcva3R6
            aUJPUjJwU3JxOGJRVG1BclFHaVA1RFEKuCIZrTmCJyfy/MNtUjYEUXghbOKb8wrZ
            54koGphmJJ3SYx7mL4GI//OaJFvrXlu4UYsJ+75MziQ7MFOq3bWjbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T19:59:22Z"
    mac: ENC[AES256_GCM,data:MeGrRkADZNL9v52eeNZHwcU0kXXSAAW7/Jl7z4bEkZmRjWQi/Ipnvx6Nu8r35LqI+52AUA9u/ZroCC9/DlERlO1Hsc3GkFzY1E+gwZqBpwtWlc/coSIHG1z9tgrlVoF99FAw2yHZZRszJNmIQjyP3q6SV6R5qZrvfa0/neT1ND0=,iv:xdgz1a7vLyw41+5FdbeRDW4WCQLiCWVgFJwW8wvSINc=,tag:WI1Vmi+AuVTxw2SwIPnzRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
# S3 backup credentials for CNPG
apiVersion: v1
kind: Secret
metadata:
    name: landl-plane-db-backup-creds
    namespace: landl
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:BIuOxlg=,iv:LO8ECO+J1wJFi7cIwzfVPpDErm9+7I9cablZ73Bfu5w=,tag:B9s09MqmaGTe4eBQaqHVHA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FGKjp7uQulM=,iv:+9I9coxq0O1jLr17+JoupNHfq0B5zpagiOWenVkpWKI=,tag:GDAVD7ASO17x1RsmnXZwXA==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUjNHMDNGTk5kRlVHM0ZT
            SWlEdVpmTFJRM00wT1FFZHBtcHU0NVVNTW44CnBqWGtpUDZxMUhzQU1aSmRldUIy
            ck9WOHdUS2NLN3JDTnB5dGsyeE01ZmMKLS0tIDhoanpnbjF2VUdDMTA3QXcva3R6
            aUJPUjJwU3JxOGJRVG1BclFHaVA1RFEKuCIZrTmCJyfy/MNtUjYEUXghbOKb8wrZ
            54koGphmJJ3SYx7mL4GI//OaJFvrXlu4UYsJ+75MziQ7MFOq3bWjbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T19:59:22Z"
    mac: ENC[AES256_GCM,data:MeGrRkADZNL9v52eeNZHwcU0kXXSAAW7/Jl7z4bEkZmRjWQi/Ipnvx6Nu8r35LqI+52AUA9u/ZroCC9/DlERlO1Hsc3GkFzY1E+gwZqBpwtWlc/coSIHG1z9tgrlVoF99FAw2yHZZRszJNmIQjyP3q6SV6R5qZrvfa0/neT1ND0=,iv:xdgz1a7vLyw41+5FdbeRDW4WCQLiCWVgFJwW8wvSINc=,tag:WI1Vmi+AuVTxw2SwIPnzRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
# Helm values (sensitive)
apiVersion: v1
kind: Secret
metadata:
    name: landl-plane-helm-values
    namespace: landl
type: Opaque
stringData:
    env.secret_key: ENC[AES256_GCM,data:PabruSXmx00XEmDbgA3cEjUTDysrBmOnJhD/npzuB8CgMMXDN/yZIkukUgen2jhvL+X5bWITj3lbv9Act8gOXA==,iv:X5K0lOaFlMBV/WpXHNDFS41skcS9/L5tHEcJP+AZyqo=,tag:+4IaYqKKFRTtjNqjsuXeBA==,type:str]
    live_server_secret_key: ENC[AES256_GCM,data:rtD6VjTrVskXEGrhfTlfsFphqr/f1RZkEj4rf6HwmCYT8dutZVBA7nhshomQxGSSmSiBxkDQeO3ZlASftYNgGg==,iv:0LWtHlw0R/dpHCHCs08ilwdIGo3RD7BuXCcSEorr/b0=,tag:q54pmUKumvpxYNh40ITfJg==,type:str]
    env.pgdb_remote_url: ENC[AES256_GCM,data:W+kHQJuKPiwLRtcc3QkSNHylX5P0f7HM9G8KSi00iEPCZ0Ry8mg67mlQu+TmvoSXXqVULoTbvwL3nXTlEDSLta/gql7t69SJwcOHi5h+rRg=,iv:gGtzYeePK2WokIhHnkyXcjEogtDGtfWTm72mRNqiA/o=,tag:x5mDVT/rCNjOsTygTTRKaw==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUjNHMDNGTk5kRlVHM0ZT
            SWlEdVpmTFJRM00wT1FFZHBtcHU0NVVNTW44CnBqWGtpUDZxMUhzQU1aSmRldUIy
            ck9WOHdUS2NLN3JDTnB5dGsyeE01ZmMKLS0tIDhoanpnbjF2VUdDMTA3QXcva3R6
            aUJPUjJwU3JxOGJRVG1BclFHaVA1RFEKuCIZrTmCJyfy/MNtUjYEUXghbOKb8wrZ
            54koGphmJJ3SYx7mL4GI//OaJFvrXlu4UYsJ+75MziQ7MFOq3bWjbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T19:59:22Z"
    mac: ENC[AES256_GCM,data:MeGrRkADZNL9v52eeNZHwcU0kXXSAAW7/Jl7z4bEkZmRjWQi/Ipnvx6Nu8r35LqI+52AUA9u/ZroCC9/DlERlO1Hsc3GkFzY1E+gwZqBpwtWlc/coSIHG1z9tgrlVoF99FAw2yHZZRszJNmIQjyP3q6SV6R5qZrvfa0/neT1ND0=,iv:xdgz1a7vLyw41+5FdbeRDW4WCQLiCWVgFJwW8wvSINc=,tag:WI1Vmi+AuVTxw2SwIPnzRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
