# ==============================================================================
# Forgejo Runner Registration Token
# ==============================================================================
# ENCRYPT WITH: sops -e -i secret.yaml
#
# Get token from: Forgejo UI > Site Administration > Actions > Runners > Create new runner
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-token
    namespace: forgejo-runners
type: Opaque
stringData:
    registration-token: ENC[AES256_GCM,data:XQlK70C1LDxiff4rI8CbZY6xZCupkvyzwEhpvncu/X78uPw+lU5i+w==,iv:nRbPqJSun+s7Ro15YtEgYfMY4okHmsnwP4H4NS53THU=,tag:XGn0D86XQl+YYJo+Ykw+ZQ==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbVZ0N0FGYlJIRjc3bDkz
            c2pGSE5BelNOakVyZGpJYVRCNmVncVRDTjFnCklsZytnMjY4Si91S08yVWZJam1u
            VUduSmk5eE5zd3Vua1JoakY3UGNsdFEKLS0tIE13R3cyWDNNZ25zcW5JM2ErZ1Nz
            aVFhNTR6bDVxQ1NSSXpndjVTTnhxREUK3kJLEytg1PhbfVxlbCzk+c0KUCzLcULQ
            gkweSGa8izn/WqLW0l3FkOlb8jA/u2IgBQUarf2e1s7At7C5EEeSdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T18:08:32Z"
    mac: ENC[AES256_GCM,data:1e8MsC9BtZJs25CW2PrxFMve0ls4OSbI5HX8y0mRT/pDV+h+SAFEQinXKEkLG6zo/HHjo9OjHDQKTWdzPyuJ1U1jTV7XEiHTFGfSbfp2uqn5gfQWdaPR/vQh0qKALk1LSADsXQFFlCKwip3X6IdnGpLf4xwukUg3qU+wa6qNQ+k=,iv:+AqQ1zfLEXDlxGd1PPYBF3od4hop8kDLEj2kKKBhhlw=,tag:SMBp6uGr5vITlKooMG9SVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
