# ==============================================================================
# Headscale API Proxy - Service
# ==============================================================================

apiVersion: v1
kind: Service
metadata:
  name: headscale-proxy
  namespace: headscale-ui
spec:
  selector:
    app: headscale-proxy
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
