# ==============================================================================
# SeaweedFS CSI Driver Helm Release
# ==============================================================================
# Enables PVC support for SeaweedFS distributed storage
# ==============================================================================

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs-csi
  namespace: seaweedfs
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: seaweedfs-csi-driver
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: seaweedfs-csi
        namespace: flux-system

  # Wait for SeaweedFS to be ready
  dependsOn:
    - name: seaweedfs
      namespace: seaweedfs

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    # Filer address (internal cluster service)
    seaweedfsFiler: seaweedfs-filer.seaweedfs.svc.cluster.local:8888

    # Storage class settings (chart uses flat keys, not nested)
    isDefaultStorageClass: true

    # Pin to stable versions (avoid :dev/:latest memory leaks)
    seaweedfsCsiPlugin:
      image: chrislusf/seaweedfs-csi-driver:v1.4.2

    mountService:
      image: chrislusf/seaweedfs-mount:v1.4.2

    # Disable file caching to prevent memory growth
    cacheCapacityMB: 0

    # CSI controller - lightweight, can run on control plane
    controller:
      replicas: 1

    # CSI node plugin - DaemonSet, runs on all nodes
    node:
      # Runs everywhere to allow mounting on any node
      tolerations:
        - operator: Exists
