# ==============================================================================
# SeaweedFS Helm Release
# ==============================================================================
# Distributed object storage with S3 API
# Uses node labels for placement (no hardcoded hostnames)
# ==============================================================================

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs
  namespace: seaweedfs
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: seaweedfs
      version: "3.x"
      sourceRef:
        kind: HelmRepository
        name: seaweedfs
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    # -------------------------------------------------------------------------
    # Master - manages topology, runs at home
    # -------------------------------------------------------------------------
    master:
      enabled: true
      replicas: 1
      nodeSelector: |
        node.h-kube.io/location: home
      affinity: |
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - gpa-server
      data:
        type: persistentVolumeClaim
        size: 1Gi
        storageClass: local-path

    # -------------------------------------------------------------------------
    # Volume - stores actual data, runs at home on bulk storage
    # Future: replicas: 2 for redundancy across gpa-server + monkeybusiness
    # -------------------------------------------------------------------------
    volume:
      enabled: true
      replicas: 1
      nodeSelector: |
        node.h-kube.io/location: home
      affinity: |
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - monkeybusiness
      dataDirs:
        - name: data1
          type: "persistentVolumeClaim"
          size: "800Gi"
          storageClass: "local-path"
          maxVolumes: 0
      rack: home
      dataCenter: default

    # -------------------------------------------------------------------------
    # Filer - S3 API endpoint, runs at home
    # -------------------------------------------------------------------------
    filer:
      enabled: true
      replicas: 1
      nodeSelector: |
        node.h-kube.io/location: home
      affinity: |
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - gpa-server
      s3:
        enabled: true
        port: 8333
        allowEmptyFolder: true
      data:
        type: persistentVolumeClaim
        size: 2Gi
        storageClass: local-path

    # -------------------------------------------------------------------------
    # S3 Gateway - runs at home
    # -------------------------------------------------------------------------
    s3:
      enabled: true
      nodeSelector: |
        node.h-kube.io/location: home
      affinity: |
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - gpa-server

    # -------------------------------------------------------------------------
    # Disable unused components
    # -------------------------------------------------------------------------
    # Note: CSI driver is deployed separately via csi-release.yaml
    cronjob:
      enabled: false
    cosi:
      enabled: false
