# ==============================================================================
# SeaweedFS Helm Release
# ==============================================================================
# Distributed object storage with S3 API
# Uses node labels for placement (no hardcoded hostnames)
# ==============================================================================

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs
  namespace: seaweedfs
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: seaweedfs
      version: "3.x"
      sourceRef:
        kind: HelmRepository
        name: seaweedfs
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    # -------------------------------------------------------------------------
    # Master - manages topology (lightweight, runs on control plane)
    # -------------------------------------------------------------------------
    master:
      enabled: true
      replicas: 1
      nodeSelector:
        node.h-kube.io/role: server
      data:
        type: persistentVolumeClaim
        size: 1Gi
        storageClass: local-path

    # -------------------------------------------------------------------------
    # Volume - stores actual data (runs on nodes with bulk storage)
    # -------------------------------------------------------------------------
    volume:
      enabled: true
      replicas: 1
      nodeSelector:
        storage.h-kube.io/bulk: "true"
      data:
        type: persistentVolumeClaim
        size: 100Gi
        storageClass: local-path
      rack: home
      dataCenter: default

    # -------------------------------------------------------------------------
    # Filer - S3 API endpoint (runs on control plane, lightweight)
    # -------------------------------------------------------------------------
    filer:
      enabled: true
      replicas: 1
      nodeSelector:
        node.h-kube.io/role: server
      s3:
        enabled: true
        port: 8333
        allowEmptyFolder: true
      data:
        type: persistentVolumeClaim
        size: 2Gi
        storageClass: local-path

    # -------------------------------------------------------------------------
    # S3 Gateway
    # -------------------------------------------------------------------------
    s3:
      enabled: true
      nodeSelector:
        node.h-kube.io/role: server

    # -------------------------------------------------------------------------
    # Disable unused components
    # -------------------------------------------------------------------------
    cronjob:
      enabled: false
    cosi:
      enabled: false
