# ==============================================================================
# Vault Helm Release
# ==============================================================================
# HashiCorp Vault - Secrets management
# Single instance, manual unseal, Raft storage on SeaweedFS
# ==============================================================================

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: vault
      version: "0.28.x"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    # -------------------------------------------------------------------------
    # Server configuration
    # -------------------------------------------------------------------------
    server:
      enabled: true

      # Single instance with Raft storage (built-in, no external DB needed)
      standalone:
        enabled: true
        config: |
          ui = true

          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }

          storage "raft" {
            path = "/vault/data"
          }

      # Run on home nodes
      nodeSelector:
        node.h-kube.io/location: home

      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values: ["monkeybusiness"]

      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi

      # Data storage - Raft data on SeaweedFS for durability
      dataStorage:
        enabled: true
        size: 1Gi
        storageClass: seaweedfs-storage

    # -------------------------------------------------------------------------
    # UI - enabled, ingress handled separately
    # -------------------------------------------------------------------------
    ui:
      enabled: true
      serviceType: ClusterIP

    # -------------------------------------------------------------------------
    # Injector - disabled for now (can enable later for sidecar injection)
    # -------------------------------------------------------------------------
    injector:
      enabled: false

    # -------------------------------------------------------------------------
    # CSI Provider - disabled for now
    # -------------------------------------------------------------------------
    csi:
      enabled: false
