# ==============================================================================
# Tofu Controller Helm Release
# ==============================================================================
# Terraform/OpenTofu GitOps controller for Flux
# ==============================================================================

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: tofu-controller
      version: "0.16.0-rc.7"
      sourceRef:
        kind: HelmRepository
        name: tofu-controller
        namespace: flux-system
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    force: true
  install:
    remediation:
      retries: 3
  values:
    # Runner uses the same image for executing Terraform
    runner:
      image:
        repository: ghcr.io/flux-iac/tf-runner
