# ==============================================================================
# S3 Backup Credentials
# ==============================================================================
# SeaweedFS with placeholder credentials (SeaweedFS S3 doesn't require auth)
# Encrypt with: sops -e -i backup-secret.yaml
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-backup-creds
    namespace: authentik
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:kMNo5hTML2NzifY=,iv:Fhc0Ei5TL0LptXnqhGitAjN+XSzNJS9agN9E1Sghr+4=,tag:qRDwEGMZEqdKpTp962IUiA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Hx0iQdh2XoAHDSg=,iv:tUvFLoyqE5ntyDYjUvPgyf4vnDy/syG7svPYKS5U3JA=,tag:RG/Ln06l47QIH6tEq/10YA==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcFZNeFRaL0hXaXNnY3JZ
            N3hwZXVreFkySzczSnNpeWd4WjRSVHZmMDFBCmNtbk9Qbm9mUVpMUTA1VDhYWXhj
            VzY4U2VqdUVuRFlnWHBma21NcUFWNW8KLS0tIHBJYVEwOGxraVIrZzNpbW81a2Zm
            ditzblMyUDFLM2VZV3JDT0JTaVQwZHcKJ2IddhZ6g3I9k4KtMXcgX2+IN13N2RyT
            /C/X5qgGCuKuUheU+zfPMTeSQTN66RaSsTHpNol3JNLR9HGHVetTKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T23:43:35Z"
    mac: ENC[AES256_GCM,data:6iiYAISnotBuIrz5Tf3c0ZBrTb5APESBFBdsneDexbEqw+JUECzJQFhgnA8uSrCqyyFOreNgAlM7n/qIoOJ8d4m+nUd2DUUgJHmU8cqnIobZEx3muCb560G8RUQxmZ0j9bWL5vKp68PxZbaiXwBDLiS/wQay5XHbdTBrATJekZc=,iv:ceaVldM+lr9liLohxr4cWT1MOk8fpd1u/+X83qXafYI=,tag:Y42XnszbQZXKTZ70oXqOJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
