# ==============================================================================
# Authentik Helm Release
# ==============================================================================
# Identity Provider / SSO for cluster services
# ==============================================================================

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: "2025.x"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system

  # Wait for database to be ready
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system

  # Allow Flux to recover from failed installs
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true

  values:
    # -------------------------------------------------------------------------
    # Global - Inject secrets via environment variables
    # -------------------------------------------------------------------------
    global:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: secret_key
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: password

    # -------------------------------------------------------------------------
    # Authentik Config
    # -------------------------------------------------------------------------
    authentik:
      error_reporting:
        enabled: false
      postgresql:
        host: authentik-db-rw.authentik.svc.cluster.local
        name: authentik
        user: authentik

    # -------------------------------------------------------------------------
    # Use external PostgreSQL (CNPG)
    # -------------------------------------------------------------------------
    postgresql:
      enabled: false  # Don't deploy bundled postgres

    # -------------------------------------------------------------------------
    # Redis - NOT NEEDED in 2025.x (removed in 2025.10)
    # -------------------------------------------------------------------------
    redis:
      enabled: false

    # -------------------------------------------------------------------------
    # Server - run on worker node (gpa-server)
    # -------------------------------------------------------------------------
    server:
      nodeSelector:
        kubernetes.io/hostname: gpa-server
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - auth.${CLUSTER_DOMAIN}
        tls:
          - secretName: authentik-tls
            hosts:
              - auth.${CLUSTER_DOMAIN}

    # -------------------------------------------------------------------------
    # Worker - run on worker node (gpa-server)
    # -------------------------------------------------------------------------
    worker:
      replicas: 1
      nodeSelector:
        kubernetes.io/hostname: gpa-server

  # Note: Secrets are injected via global.env instead of valuesFrom
  # This ensures they're passed directly as environment variables
  # Secret key is in secrets.yaml (SOPS encrypted)
