# ==============================================================================
# Authentik Helm Release
# ==============================================================================
# Identity Provider / SSO for cluster services
# ==============================================================================

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: "2024.x"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system

  # Wait for database to be ready
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system

  values:
    # -------------------------------------------------------------------------
    # Authentik Config
    # -------------------------------------------------------------------------
    authentik:
      secret_key: ""  # Will be set from secret
      error_reporting:
        enabled: false
      postgresql:
        host: authentik-db-rw.authentik.svc.cluster.local
        name: authentik
        user: authentik
        password: ""  # Will be set from secret

    # -------------------------------------------------------------------------
    # Use external PostgreSQL (CNPG)
    # -------------------------------------------------------------------------
    postgresql:
      enabled: false  # Don't deploy bundled postgres

    # -------------------------------------------------------------------------
    # Redis (embedded)
    # -------------------------------------------------------------------------
    redis:
      enabled: true

    # -------------------------------------------------------------------------
    # Server
    # -------------------------------------------------------------------------
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - auth.kube.datamountainsolutions.com
        tls:
          - secretName: authentik-tls
            hosts:
              - auth.kube.datamountainsolutions.com

    # -------------------------------------------------------------------------
    # Worker
    # -------------------------------------------------------------------------
    worker:
      replicas: 1

  # -------------------------------------------------------------------------
  # Values from Secrets
  # -------------------------------------------------------------------------
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: secret_key
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-db-app
      valuesKey: password
      targetPath: authentik.postgresql.password

---
# ==============================================================================
# Authentik Secret Key
# ==============================================================================
# Generate with: openssl rand -base64 32
# TODO: Use SOPS to encrypt this

apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: authentik
type: Opaque
stringData:
  secret_key: "KIZZyLOM4x+Lu+leXb4lQpl/3ifchWbhInKyZbo1fvQ="
