# ==============================================================================
# Quant Namespace
# ==============================================================================
# Financial infrastructure - IBKR connector, market data, portfolio tracking
# ==============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: quant
  labels:
    name: quant
