# GitRepository - Flux watches this for changes
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homedia
  namespace: flux-system
spec:
  interval: 5m
  url: ssh://git@forgejo.datamountainsolutions.com:2222/mkultra/homedia
  ref:
    branch: main
  secretRef:
    name: flux-system
