# ==============================================================================
# Airbyte Helm Release (V2)
# ==============================================================================
# Data integration platform - ELT connectors
# Uses CNPG PostgreSQL, logs to SeaweedFS
# ==============================================================================

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airbyte
  namespace: airbyte
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: airbyte
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: airbyte
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system

  values:
    # -------------------------------------------------------------------------
    # Global settings
    # -------------------------------------------------------------------------
    global:
      database:
        type: external
        host: airbyte-db-rw.airbyte.svc.cluster.local
        port: 5432
        name: airbyte
        user: airbyte
        secretName: airbyte-db-app
        userSecretKey: username
        passwordSecretKey: password

      storage:
        type: s3
        bucket:
          log: airbyte-storage
          state: airbyte-storage
          workloadOutput: airbyte-storage
          activityPayload: airbyte-storage
        s3:
          endpoint: http://seaweedfs-s3.seaweedfs.svc.cluster.local:8333
          authenticationType: credentials
          accessKeyId:
            secretName: airbyte-storage-creds
            secretKey: S3_ACCESS_KEY
          secretAccessKey:
            secretName: airbyte-storage-creds
            secretKey: S3_SECRET_KEY
          region: us-east-1

      jobs:
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 4
            memory: 8Gi

    # -------------------------------------------------------------------------
    # Disable bundled dependencies (using CNPG + external storage)
    # -------------------------------------------------------------------------
    postgresql:
      enabled: false

    minio:
      enabled: false

    # -------------------------------------------------------------------------
    # Server - API server, runs at home
    # -------------------------------------------------------------------------
    server:
      nodeSelector:
        node.h-kube.io/location: home
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values: ["monkeybusiness"]
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 2Gi

    # -------------------------------------------------------------------------
    # Webapp - UI, runs at home
    # -------------------------------------------------------------------------
    webapp:
      nodeSelector:
        node.h-kube.io/location: home
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values: ["monkeybusiness"]
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      ingress:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: airbyte.${CLUSTER_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: airbyte-tls
            hosts:
              - airbyte.${CLUSTER_DOMAIN}

    # -------------------------------------------------------------------------
    # Worker - heavy lifting, prefers monkeybusiness (more RAM)
    # -------------------------------------------------------------------------
    worker:
      nodeSelector:
        node.h-kube.io/location: home
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values: ["monkeybusiness"]
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 2
          memory: 4Gi

    # -------------------------------------------------------------------------
    # Workload launcher - prefers monkeybusiness (more RAM)
    # -------------------------------------------------------------------------
    workloadLauncher:
      nodeSelector:
        node.h-kube.io/location: home
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values: ["monkeybusiness"]
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 2Gi
