# ==============================================================================
# Airbyte S3 Storage Credentials
# ==============================================================================
# SOPS encrypted - edit with: sops cluster/infrastructure/services/airbyte/storage-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: airbyte-storage-creds
    namespace: airbyte
type: Opaque
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:qigce1Y=,iv:5KXDXgusIFOI97BPtPfaY3A3spcAbH+lLbxb5DlGPO4=,tag:F5PAloZdEmQuS/yiCiXvFg==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:U7bKhpQ=,iv:F+lBAK2NC/wPXISTFiVOEbyjmY/6zbS7r9BjV+X/lbU=,tag:7m6DA3CATf/dw/6PIQo7kQ==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwS0U0U01NR3VDZHJFS2tP
            TWtSNEhKRjhNSmQyZ1JBY01oanpVdXZiZnh3CmR3aGpRM3B1ajZHUzYwZWpxUmN5
            alJYaUpnUDNUazVvSkhuTkVSUVZBVlEKLS0tIEpCbVdRaGRXdVpJQlZ2dnloN085
            Q04xK0xsMU0zNWJXWDROWnB1N0g4bWcKrd/v5ssSdAgunsUxXcsrAUhhgjMLjDme
            fJh+XiHlqsQ/utWo7JM8L7WOBlFkkNGQbf75/wBsVTLnFni3kiEuxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T07:39:58Z"
    mac: ENC[AES256_GCM,data:39ziS7WPJQRlYFTfK6NhqK1x+/nf7UtO1LkCxAhXXW6uR59OmmbAad0Du5+dJRvIytAK4fijqlk7Kej4ich0zXMxbILjzhf7Jnl60ljvduRIQcZltvw1ZHVHQ7M/rmUkKZOhcYNzgq+0uwWRuDI/F/cI5aNf4se1pA5+UQiyr+w=,iv:8oM4i8XeflalP+EvCH8Oxq0A3bHXYH954/Q7/YwVscs=,tag:vGvvCR1cktm0Ie/zYa+oHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
