# ==============================================================================
# Airbyte Vault Token
# ==============================================================================
# Token for Airbyte to authenticate with Vault
# UPDATE AFTER VAULT INIT: Replace 'placeholder' with actual Vault token
# Encrypt with: sops -e -i vault-token-secret.yaml
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: airbyte-vault-token
    namespace: airbyte
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:0qe2eM+ICkgS/bZJgKH7esJ9tEMU5gp/wi8dZ5DA0tcAQXU=,iv:arzjUzdWDTB58JH4FfOymjjHberMb1vpl7R7wqR6vf8=,tag:5wWndlZz4g5gzpksWm+7mA==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaFpydUhxU1hWQmhVZFlB
            SGtHWXpXQ2dDc1VTdXA4UGQ4c1FuMU5HSkRvClpGcjhLcFFXaWh5Q3NFVEtlK2lz
            NWJLZlduV1d3YThWYkdjUzBrNWc3bUUKLS0tIFgvRzYzZlBHL1NJVjJvTDluZk1u
            dkhrLzdNTVRNT21JQ1RSTDUyc3NTSXMK+Mq4ZTNbZQ/Qre/LfyG3G+bfqWx4M36n
            IuABJ4bu1GSSXUsUYRX4N5z9ovpEk/txeU4t802wW4DsCqhiWF/+Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T22:11:22Z"
    mac: ENC[AES256_GCM,data:ahnsEFIJQfsBQoVkH0XGBSFRtbkNZOUsy/aZDF7MgQUsrvoqXOO97pWvURE3ZsrrnGMu/o8L/ckz2QS7Hzk5SrqV2IDBmBvm+yhbhMTxM8/Lje4sKbircHnqGbWQjfj2tUKsCUdSNW3okuYeZv9CQltnfyq6FROHyHMFGknPB8I=,iv:T4u947VA70kxCbks1mxqXUHmt4XGDSErGfTddNvdtAA=,tag:Ptle3bo7sC8tXiAlVxuPpw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
