# ==============================================================================
# Airbyte Vault Token
# ==============================================================================
# Token for Airbyte to authenticate with Vault
# UPDATE AFTER VAULT INIT: Replace 'placeholder' with actual Vault token
# Encrypt with: sops -e -i vault-token-secret.yaml
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: airbyte-vault-token
    namespace: airbyte
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:fuw5vhRDG0xpMizsI1JcULPawDV4tI5lcIYfoDVxwW6ts6IkVynrldz6aSFdBwAqrKsjJ8mQvDuKQT2DCd8W9wFUxR5kMGLQ3XztUgeZ1Wn4k8EMNfMCcMp9WF0c6LI=,iv:XJZayKApvHqHrABilEJphLfsljLrn8nbaDKe5SpJHl4=,tag:49L5OWsZR4l9YF3v2YV1XQ==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEa0g1a2ZVbno0MGpsWDlV
            SVhiYmRQUTY1dGw1RmxkTm5Tck15cXhlZ2tnCjZQQUQ4MDIvVzczd0VNWjVrYU52
            UnVtOERBdndDd1dHVHVrZmgrNUNPVU0KLS0tIEhwNytnQy9jV2VWY1J3cTNFQnpk
            bDZKQUVUd2dNS1g4WnhnS0FjT3h5ZHcKFyZN7okyj9tR/Dql+BELzKp+sIueDspJ
            W+1dSw66NjKor90cre6QJPKgSOcSK5iYBkm2sHWnPZoDfkucLzCOxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T22:36:04Z"
    mac: ENC[AES256_GCM,data:jTfmat+rcS9QA4AWYauP9F3omqiPKK+95SfVpgAIzlRe9pO/bw1iLgBV4yTu4fxRh8Mbx6SEs0UycY8by+atljsLwtFC8UC8+k2rSQgT3Ys0s8xNjMgwgf1B9MQRRmV41YWA30AaxeAZEOVYEubN+3mm+w0vwilVtoTQXAg3PkM=,iv:JKQFw450iTkX3TLN+JZhBBYtuqeNsC0pvNa5JEVO9lA=,tag:Aa9mR7cREhm6johA6wrZdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
