# ==============================================================================
# Homepage Helm Release
# ==============================================================================
# Admin dashboard for all cluster services
# Docs: https://gethomepage.dev/
# ==============================================================================

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true

  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: latest

    # -------------------------------------------------------------------------
    # Enable Kubernetes integration
    # -------------------------------------------------------------------------
    enableRbac: true
    serviceAccount:
      create: true
      name: homepage

    # -------------------------------------------------------------------------
    # Use our ConfigMap for configuration
    # -------------------------------------------------------------------------
    config:
      useExistingConfigMap: homepage-config

    # -------------------------------------------------------------------------
    # Ingress - exposed at home.kube.datamountainsolutions.com
    # -------------------------------------------------------------------------
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.middlewares: kube-system-authentik-auth@kubernetescrd
        hosts:
          - host: home.${CLUSTER_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: homepage-tls
            hosts:
              - home.${CLUSTER_DOMAIN}

    # -------------------------------------------------------------------------
    # Environment Variables
    # -------------------------------------------------------------------------
    env:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: "home.${CLUSTER_DOMAIN}"

    # -------------------------------------------------------------------------
    # Resources
    # -------------------------------------------------------------------------
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
